export default {
  VPA_TYPE: {
    INVALID: { value: 0, text: 'Invalid' },
    SERVICE: { value: 1, text: 'Service' },
    MCAST_ENTERPRISE: { value: 2, text: 'Mcast Enterprise' },
    MCAST_SERVICE: { value: 3, text: 'Mcast Service' },
    DYNAMIC: { value: 4, text: 'Dynamic' },
    STANDARD: { value: 5, text: 'Standard' },
    MCM_IPC: { value: 6, text: 'MCM IPC' },
    VIP_VLAN: { value: 7, text: 'VIP VLAN' },
    ERP_VLAN: { value: 8, text: 'ERP VLAN' },
    MTP_VLAN: { value: 9, text: 'MTP VLAN' },
    UNP_DYNAMIC: { value: 10, text: 'UNP Dynamic' },
    DYNAMIC_REMOTE: { value: 11, text: 'Dynamic Remote' },
    BVLAN: { value: 12, text: 'BVLAN' },
    CONTROL_BVLAN: { value: 13, text: 'Control BVLAN' },
    EVB_VLAN: { value: 14, text: 'EVB VLAN' },
    VCM_IPC: { value: 15, text: 'VCM IPC' },
    FCOE: { value: 16, text: 'FCoE' },
    OPEN_FLOW: { value: 17, text: 'OpenFlow' },
    PVLAN_P: { value: 19, text: 'PVLAN-P' },
    PVLAN_I: { value: 20, text: 'PVLAN-I' },
    PVLAN_C: { value: 21, text: 'PVLAN-C' },
  },
  VPA_STATE: {
    FORWARDING: { value: 0, text: 'Forwarding' },
    BLOCKING: { value: 1, text: 'Blocking' },
    INACTIVE: { value: 2, text: 'Inactive' },
    INVALID: { value: 3, text: 'Invalid' },
    DHL_BLOCKING: { value: 4, text: 'DHL-Blocking' },
  },
  GIOITINH: {
    NAM: { value: 1, text: 'Nam' },
    NU: { value: 2, text: 'nu' },
  },
  LOAITAIKHOAN: {
    ADMIN: { value: 'admin', text: 'Admin' },
    USER: { value: 'user', text: 'User' },
  },
};